### ISSUE TITLE
Review Ticket (Week 8)

### ISSUE THREAD

**Issue by mistylavender** [4disease/p1-donuts-new#32]
**PBL:**
_Frontend work: Not Yet Completed_

- [x] Cleaning up the main page
- [x] Cleaning up tasks page
- [x] Cleaning up the calendar

_Backend work: Not Yet Completed_
- [ ] Login database
- [ ] Link to task information + display on frontend

**ASCII Art Minilab:**
_Frontend work: Not Yet Completed_

- [ ] Connect algorithm to picture of donuts

_Backend work: Not Yet Completed_
- [x] Grayscale of Image
- [x] Blocks using 2D Arrays
- [x] Converting Grayscale to ASCII

**Comment by jli615** [comment]
Wonderful stuff - I really like how clean the front end looked, and I really liked the idea of the chatbot. It would be great if you could make the calendar page less confusing

**Comment by BillyCherres** [comment]
wow thiis was really cool! I liked your code and how nice the front end looked. Some advice I would give is for you guys to use blue prints and organize your code better.

**Comment by PrishaMaiti** [comment]
Your front end looked very user-friendly and interactive!

**Comment by ryanmgds** [comment]
Great presentation! nice frontend and user friendly work. The chat was a nice feature.

**Comment by 4disease** [comment]
GRADING
ASCII Lab - 3/3
Group present - 4.5/5
Unit 8
Kira - 2/2
Natasha - 2/2
Ridhima - 2/2
Sam - 2/2
Adi - 0/2
_________
In summary...
Kira - 9.5/10
Natasha - 9.5/10
Ridhima - 9.5/10
Sam - 9.5/10
Adi - 7.5/10
